"""add cuisine model

Revision ID: 38ea20440b2d
Revises: 12fb445aa46f
Create Date: 2026-07-12 09:56:19.354721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ea20440b2d'
down_revision: Union[str, Sequence[str], None] = '12fb445aa46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuisines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cuisines_slug'), 'cuisines', ['slug'], unique=True)
    op.add_column('recipes', sa.Column('cuisine_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_recipes_cuisine'), table_name='recipes')
    op.create_foreign_key(None, 'recipes', 'cuisines', ['cuisine_id'], ['id'], ondelete='SET NULL')
    op.drop_column('recipes', 'cuisine')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('cuisine', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_index(op.f('ix_recipes_cuisine'), 'recipes', ['cuisine'], unique=False)
    op.drop_column('recipes', 'cuisine_id')
    op.drop_index(op.f('ix_cuisines_slug'), table_name='cuisines')
    op.drop_table('cuisines')
    # ### end Alembic commands ###
