"""added ingredient model

Revision ID: 71b30cf605b0
Revises: 157179a3e030
Create Date: 2026-07-20 13:57:05.256785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71b30cf605b0'
down_revision: Union[str, Sequence[str], None] = '157179a3e030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.drop_index(op.f('ix_ingredient_name'), table_name='ingredient')
    op.drop_index(op.f('ix_ingredient_slug'), table_name='ingredient')
    op.drop_table('ingredient')
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('ingredient',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=220), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ingredient_pkey'))
    )
    op.create_index(op.f('ix_ingredient_slug'), 'ingredient', ['slug'], unique=True)
    op.create_index(op.f('ix_ingredient_name'), 'ingredient', ['name'], unique=True)
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
